conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lunch_poll.urls'))
]

lunch_poll/urls.py
from django.urls import path

from . import views

app_name = 'lunch_poll'


urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/vote/', views.VoteView.as_view(), name='vote'),
]

lunch_poll/models.py
from django.db import models
from django.utils import timezone


class Lunch(models.Model):

    nickname = models.CharField(max_length=50)
    # user = models.CharField(max_length=100)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nickname


class Location(models.Model):
    lunch = models.ForeignKey(Lunch, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default='generic')
    description = models.TextField(default=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.title

lunch_poll/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseRedirect

from .models import Lunch, Location


class HomeView(TemplateView):

    # view should be styled and have a listing of current lunches

    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        lunches = Lunch.objects.order_by('date')[:5]

        context = {
            'latest_lunches': lunches
        }

        return context


class DetailView(TemplateView):
    # view should show details of lunch,
    # along with a list of locations

    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        available_locations = Location.objects.all()
        vote_pk = self.kwargs.get('pk')
        vote = Lunch.objects.get(pk=vote_pk)
        context = {
            'details': available_locations,
            'vote': vote,
        }

        return context


class ResultsView(TemplateView):

    # view should show listing of locations for lunch
    # along with number of votes each location received

    template_name = 'results.html'

    def get_context_data(self, **kwargs):

        vote_pk = self.kwargs.get('pk')
        vote = Lunch.objects.get(pk=vote_pk)
        context = {
            'vote': vote
        }

        return context


class VoteView(View):

    # view should receive a POST request from the form on
    # Detail page and increase vote count for selected location

    def post(self, reqest, **kwargs):
        vote_pk = self.kwargs.get('pk')
        vote = Lunch.objects.get(pk=vote_pk)
        lunch_spot_voted_id = self.request.POST.get('location')

        selected_lunch_location = vote.location_set.get(pk=lunch_spot_voted_id)

        selected_lunch_location.votes += 1
        selected_lunch_location.save()

        results_url = reverse('lunch_poll:results', args=(vote.pk,))

        return HttpResponseRedirect(results_url)

lunch_poll/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    {#          {% load static %}#}

    {#        <link rel="stylesheet" type="text/css" href="{% static "styles.css" %}">#}

    <link rel="stylesheet" type="text/css" href="../static/styles.css">
    <title>Peas On Earth</title>
</head>
<body>
<div class="bg">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'lunch_poll:home' %}">Peas On Earth &#9996;</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'lunch_poll:home' %}">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Create Poll</a>
                    </li>
                </ul>
            </div>
        </nav>


        <!--
        <nav id="primary-nav" class="small">
            <a href="#">Main</a>

            <ul class="navbar-nav">

                <li class="float-left">
                    Lunch Not War
                </li>

                <li class="float-right">
                    <a href="#">Create Poll</a>
                </li>

            </ul>
        </nav>

        <div class='body'>
            <div class="container hero">

            </div>
        -->
        {% block content %}
        {% endblock %}

    </div>
</div>

{% load static %}
<script type="text/javascript" src="{% static "main.js" %}"></script>

</body>
</html>

lunch_poll/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="voting">

        <form class="center" action="{% url 'lunch_poll:vote' vote.id %}" method="post">
            {% csrf_token %}


            {% for location in vote.location_set.all %}
                <ul>
                    <li>
                        <label for="Location{{ forloop.counter }}">
                            <h4 class="col">{{ location.title }}</h4>
                        </label>

                        <div class="col">
                            Select:
                            <input type="radio" name="location" id="location{{ forloop.counter }}"
                                   value="{{ location.id }}">
                    </li>
                </ul>
            {% endfor %}


    </div>

    <div class="vote-button">
        <button type="submit" class="vote-button btn btn-primary" value="Vote">Vote</button>
    </div>
    </form>
    </div>

{% endblock %}

lunch_poll/templates/home.html
{% extends 'base.html' %}


{% block content %}
    <div class="poll-selection">
    <h1 class="text-center">Make Lunch Not War</h1>
    <h2 class="text-center">Who are you having lunch with?</h2>

    {% if latest_lunches %}
        <ul class="list-group">
            {# Loop over the latest_contests list and get each contest #}
            {% for lunch in latest_lunches %}
                {# We can build a url with the name of our path using the url template tag #}
                <li class="text-center link-adjust"><a href="{% url 'lunch_poll:detail' lunch.id %}">{{ lunch.nickname }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="container">
            <footer class="fixed-button">
                <p class="text-muted">Nothing to see here.</p>
            </footer>
        </div>
        </div>
    {% endif %}
{% endblock %}

lunch_poll/templates/results.html
{% extends 'base.html' %}

{% block content %}
<ul class="center">
    {% for location in vote.location_set.all %}
        <li> {{ location.title }} -- {{ location.votes }} vote{{ location.votes|pluralize }}</li>
    {% endfor %}
</ul>
    <div class="center">
    <a href="{% url 'lunch_poll:detail' vote.id %}">Vote again?</a>
    </div>
{% endblock %}